name: Run Robot Framework Tests

on:
  push:
    branches: [ main, Test ]
  pull_request:
    branches: [ main, Test ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install webdriver-manager

    - name: Run Robot Framework tests
      run: |
        robot selenium_robot_login_test/tests

    - name: Upload Robot Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: robot-test-reports
        path: |
          **/output.xml
          **/log.html
          **/report.html
